### ISSUE TITLE
你好，看您的论文说的是t0,t1,t2三个时间点的输入,，但是数据集中landsat和modis数据都是同一个日期的，所以您是怎样设置的呢

### ISSUE THREAD

**Issue by aiyayou725** [theonegis/rsfn#1]

**Comment by aiyayou725** [comment]
你好，看您的论文说的是t0,t1,t2三个时间点的输入,，但是数据集中landsat和modis数据都是同一个日期的，所以您是怎样设置的呢

**Comment by theonegis** [comment]
For example, if you want to generate the Landsat-like image on Dec. 15 (t1), then you have to prepare two MODIS-Landsat data pairs before and after Dec. 15. Let’s say, Nov. 30 (t0) and Dec. 31 (t2) if the data are available.  And of course, you must have the MODIS data on Dec. 15. The two MODIS-Landsat data pairs on t0 and t1 and the MODIS data on t1 are the model inputs.
